In [4]:
from sklearn import  datasets
from sklearn.model_selection import train_test_split

iris=datasets.load_iris()

x=iris.data
y=iris.target

x_train,x_test,y_train,y_test= train_test_split(x,y)

In [10]:
from sklearn.neural_network import MLPClassifier

clf=MLPClassifier()
clf.fit(x_train,y_train)
print(clf.score(x_test,y_test))
print(clf.coefs_[0].shape)
#print(clf.intercept_[0].shape)

0.9473684210526315
(4, 100)


C:\Anaconda\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


AttributeError: 'MLPClassifier' object has no attribute 'intercept'

In [64]:
## forward propogation 
## without hidden layer

import  numpy as np

x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0,0,0,1]]).T
x.shape,y.shape

((4, 2), (4, 1))

In [65]:
def Sig(z):
    return 1/(1+ np.exp(-z))
# till here same

In [17]:
weights=2*np.random.random((2,1))-1  #range b/w -1 to 1
bias=2*np.random.random(1)-1


In [20]:
output0 = x
output = Sig(np.dot(output0,weights)+bias)
output

array([[0.27055518],
       [0.36223428],
       [0.39979672],
       [0.50495375]])

In [23]:
## With hidden layer

wh=2*np.random.random((2,2))-1  #range b/w -1 to 1
bh=2*np.random.random((1,2))-1

wo=2*np.random.random((2,1))-1  #range b/w -1 to 1
bo=2*np.random.random((1,1))-1



In [24]:
output0=x
outputhidden= Sig(np.dot(output0,wh)+bh)

output= Sig(np.dot(outputhidden,wo)+bo)
output

array([[0.15700185],
       [0.15983646],
       [0.17125251],
       [0.17544858]])

In [66]:
##  including Backward propogation
## updating weight to minimize errors

def derivativeSig(z):
    return Sig(z)*(1-Sig(z))

In [62]:
## for no hidden layer

weights=2*np.random.random((2,1))-1  #range b/w -1 to 1
bias=2*np.random.random(1)-1
lr=0.1
weights,bias

(array([[-0.24879532],
        [-0.34661969]]), array([-0.38158945]))

In [58]:
for iter in range(10000):
    output0=x
    output = Sig(np.dot(output0,weights)+bias)
    
    first_term=output-y
    input_for_last_layer=np.dot(output0,weights)+bias
    second_term= derivativeSig(input_for_last_layer)
    first_two=first_term*second_term
    
    changes=np.array([[0.0],[0.0]])
    
    for i in range(2):
        for j in range(4):
            changes[i][0]+= first_two[j][0]*output0[j][i]
    weights=weights-lr*changes
    bias_change=0.0
    for j in range(4):
        bias_change+=first_two[j][0]*1
    bias=bias-lr*bias_change

output = Sig(np.dot(x,weights)+bias)
weights,bias,output

(array([[5.46701272],
        [5.46701272]]), array([-8.29326653]), array([[2.50133272e-04],
        [5.59218479e-02],
        [5.59218478e-02],
        [9.33439132e-01]]))

In [63]:
## optimized using vector multiplication

for iter in range(10000):
    output0=x
    output = Sig(np.dot(output0,weights)+bias)
    
    first_term=output-y
    input_for_last_layer=np.dot(output0,weights)+bias
    second_term= derivativeSig(input_for_last_layer)
    first_two=first_term*second_term
    
    changes=np.dot(output0.T,first_two)
    weights=weights-lr*changes
    bias_change=np.sum(first_two)
    bias=bias-lr*bias_change

output = Sig(np.dot(x,weights)+bias)
weights,bias,output

(array([[5.47480039],
        [5.47480039]]), array([-8.30491328]), array([[2.47237648e-04],
        [5.57184582e-02],
        [5.57184583e-02],
        [9.33682802e-01]]))

In [69]:
## for 1 hidden layer

wh=2*np.random.random((2,2))-1  #range b/w -1 to 1
bh=2*np.random.random((1,2))-1
wo=2*np.random.random((2,1))-1
bo=2*np.random.random((1,1))-1
lr=0.1
weights,bias

(array([[5.47480039],
        [5.47480039]]), array([-8.30491328]))

In [73]:

for iter in range(10000):
    output0=x
    input_hidden=np.dot(output0,wh)+bh
    output_hidden=Sig(input_hidden)
    input_for_output_layer=np.dot(output_hidden,wo)+bo
    output=Sig(input_for_output_layer)
    
    first_term_output_layer=output-y
    second_term_output_layer= derivativeSig(input_for_last_layer)
    first_two_output_layer=first_term_output_layer*second_term_output_layer
    first_term_hidden_layer=first_term_output_layer*second_term_output_layer
    
    first_term_hidden_layer=np.dot(first_term_output_layer,wo.T)
    second_term_hidden_layer=derivativeSig(input_hidden)
    first_two_hidden_layer=first_term_hidden_layer*second_term_hidden_layer
    
    changes_output=np.dot(output_hidden.T,first_two_output_layer)
    changes_output_bias=np.sum(first_two_output_layer, axis=0, keepdims=True)
    
    changes_hidden=np.dot(output0.T,first_two_hidden_layer)
    changes_hidden_bias= np.sum(first_two_hidden_layer,axis=0,keepdims=True)
    
    
    wo=wo-lr*changes_output
    b0=bo-lr*changes_output_bias
    wh=wh-lr*changes_hidden
    bh=bh-lr*changes_hidden_bias

output0=x
input_hidden=np.dot(output0,wh)+bh
output_hidden=Sig(input_hidden)
input_for_output_layer=np.dot(output_hidden,wo)+bo
output=Sig(input_for_output_layer)
output,wh,bh,wo,bo

(array([[0.37018268, 0.37018266],
        [0.37001117, 0.37001117],
        [0.36998453, 0.36998453],
        [0.36990813, 0.36990812]]), array([[1.07653871, 0.36928447],
        [0.87962644, 0.29111287]]), array([[6.88622481, 6.44672088]]), array([[-0.86561118, -0.86494211],
        [-0.54834706, -0.54901662]]), array([[0.88077337]]))